### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by HariboTer** [WinDanesz/WizardryGolems#1]
This mod is unfortunately causing a crash on startup for me with my humble selection of mods, here's the crash report: 
[crash-2020-12-07_03.01.45-client.txt](https://github.com/WinDanesz/WizardryGolems/files/5650128/crash-2020-12-07_03.01.45-client.txt)

**Comment by Maxzilla60** [comment]
Getting the same sort of error.

**Comment by Sunconure11** [comment]
Same issue here.

https://pastebin.com/grf9EFug

@WinDanesz

**Comment by WinDanesz** [comment]
Hi guys, I'm aware of that issue, its probably a build error, I'll recompile the code and upload a fixed version soon. Cheers

**Comment by WinDanesz** [comment]
The fixed version will be available with the link below. Would appreciate if you can give it a try and let me know if it works. Thanks!
https://www.curseforge.com/minecraft/mc-mods/wizardry-golems/files/3137000

**Comment by Maxzilla60** [comment]
I've tested it and everything seems to be working well. 😁

Thanks for the quick turnaround!

**Comment by WinDanesz** [comment]
Thanks, have fun
