### ISSUE TITLE
[Bug] Server Crash

### ISSUE THREAD

**Issue by EmyLightsaber** [WinDanesz/WizardryGolems#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

I updated Wizardry Golems to the latest version of 1.3.1, and after trying to boot up my pack, I got the following server-crash:

[crash-2024-02-25_22.41.14-server.txt](https://github.com/WinDanesz/WizardryGolems/files/14398134/crash-2024-02-25_22.41.14-server.txt)

### Expected behaviour

I expected it to let me play with my existing world.

### Steps to reproduce

1. Boot the Server.
2. Server starts
3. Server crashes

### Environment (Singleplayer/Server, etc.)

LAN game/Server

### Mod version

1.3.1

### Forge version

1.12.2 14.23.5.2860

### Other mods

Vorps Reborn pack. [https://www.curseforge.com/minecraft/modpacks/vorps-reborn/files/5127109/dependencies](url)

**Comment by EmyLightsaber** [comment]
So, I had to go back to 1.2.0 to find a working version that didn't crash.

**Comment by WinDanesz** [comment]
1.3.2 will be up soon to fix it
